apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: dockbix-agent-xxl
  labels:
    tier: monitoring
    app: dockbix-agent-xxl
    version: v1
spec:
  template:
    metadata:
      labels:
        name: dockbix
    spec:
      # Filter to specific nodes:
      # nodeSelector:
      #  app: dockbix
      hostPID: true
      hostIPC: true
      hostNetwork: false
      containers:
        - image: monitoringartist/dockbix-agent-xxl-limited
          name: dockbix
          securityContext:
             privileged: true
          resources:
            requests:k
              cpu: 0.15

          env:
            - name: ZA_Server
              value: "zabbix-server"
            - name: ZA_ServerActive
              value: "zabbix-server"

          volumeMounts:
            - name: rootfs
              mountPath: /rootfs
            - name: run
              mountPath: /var/run/
      volumes:
        - name: rootfs
          hostPath:
              path: /
        - name: run
          hostPath:
              path: /var/run/
