apiVersion: v1
kind: Service
metadata:
  name: zabbix-frontend
  labels:
    app: zabbix
    tier: frontend
spec:
  ports:
  - port: 80
    targetPort: 80
    name: zabbix-web
  selector:
    app: zabbix
    tier: zabbix-frontend
---
apiVersion: v1
kind: Service
metadata:
  name: zabbix-db
  labels:
    app: zabbix
    tier: db
spec:
  ports:
  - port: 3306
    targetPort: 3306
    name: zabbix-db
  selector:
    app: zabbix
    tier: zabbix-db
---
apiVersion: v1
kind: Service
metadata:
  name: zabbix-backend
  labels:
    app: zabbix
    tier: backend
spec:
  ports:
  - port: 10051
    targetPort: 10051
    name: zabbix-trapper
  - port: 10052
    targetPort: 10052
    name: zabbix-jmx
  selector:
    app: zabbix
    tier: zabbix-backend
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: zabbix-frontend
  labels:
    app: zabbix
    tier: frontend
spec:
  replicas: 3
  selector:
    app: zabbix
    tier: frontend
  template:
    metadata:
      labels:
        name: zabbix-frontend
        app: zabbix
        tier: frontend
    spec:
      containers:
        - name: zabbix-frontend
          image: zabbix/zabbix-server-2.4
          ports:
          - containerPort: 80
          env:
          - name: ZS_DBUser
            value: zabbix
          - name: ZS_DBPassword
            value: my_password
          - name: ZS_StartPollers
            value: 0
          - name: ZS_StartPollersUnreachable
            value: 0
          - name: ZS_StartTrappers
            value: 0
          - name: ZS_StartPingers
            value: 0
          - name: ZS_StartDiscoverers
            value: 0
          - name: ZS_StartHTTPPollers
            value: 0
          - name: ZS_StartTimers
            value: 0
          - name: ZS_StartJavaPollers
            value: 0
          - name: ZS_StartVMwareCollectors
            value: 0
          - name: ZS_StartSNMPTrapper
            value: 0
          - name: ZS_StartDBSyncers
            value: 0
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: zabbix-db
  labels:
    app: zabbix
    tier: zabbix-db
spec:
  replicas: 1
  selector:
    app: zabbix
    tier: zabbix-db
  template:
    metadata:
      labels:
        name: zabbix-db
        app: zabbix
        tier: zabbix-db
    spec:
      containers:
        - name: zabbix-db
          image: zabbix/zabbix-db-mariadb
          ports:
          - containerPort: 3306
            name: mariadb
          env:
          - name: MARIADB_USER
            value: zabbix
          - name: MARIADB_PASS
            value: my_password
          volumeMounts:
          - name: zabbix-db-storage
            mountPath: /var/lib/mysql
      volumes:
      - name: zabbix-db-storage
        persistentVolumeClaim:
          claimName: zabbix-db-claim
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: zabbix-backend
  labels:
    app: zabbix
    tier: backend
spec:
  replicas: 1
  selector:
    app: zabbix
    tier: backend
  template:
    metadata:
      labels:
        name: zabbix-backend
        app: zabbix
        tier: backend
    spec:
      containers:
        - name: zabbix-backend
          image: zabbix/zabbix-server-2.4
          ports:
          - containerPort: 10051
            name: zabbix-trapper
          - containerPort: 10052
            name: zabbix-jmx
          env:
          - name: ZS_DBUser
            value: zabbix
          - name: ZS_DBPassword
            value: my_password